import type * as Preset from '@docusaurus/preset-classic'
import type { Config } from '@docusaurus/types'
import { themes as prismThemes } from 'prism-react-renderer'

const organization = 'therealm-tech'
const project = 'mire'
const repository = `https://github.com/${organization}/${project}`

const config: Config = {
  title: 'mire',
  tagline: 'A test pattern for model endpoints',
  favicon: 'img/favicon.svg',

  future: {
    v4: true,
    faster: true,
  },

  url: `https://${organization}.github.io`,
  baseUrl: `/${project}/`,
  organizationName: organization,
  projectName: project,
  trailingSlash: false,

  // The docs tree under `docs/` is generated by `scripts/sync-docs.mts` from the
  // repository's own markdown. A link that no longer resolves means the sync
  // manifest has drifted from the files, which is worth a red build rather than
  // a line nobody reads.
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    // `.md` is CommonMark, `.mdx` is MDX. The synced documents are prose that
    // was never written for MDX: they carry `${ stage.x }` and `{{ messages }}`
    // in running text, which an MDX parser reads as an expression and rejects.
    format: 'detect',
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  themes: ['@docusaurus/theme-mermaid'],

  presets: [
    [
      'classic',
      {
        docs: {
          path: 'docs',
          routeBasePath: 'docs',
          sidebarPath: './sidebars.ts',
          // An ADR is addressed by its number: `0001-…` is the file's name in
          // the repository and has to stay the page's name here, rather than
          // being read as a sort key and stripped.
          numberPrefixParser: false,
          // Every generated page carries a `custom_edit_url` pointing at the
          // file it was synced from, so this only has to cover the ones that do
          // not — of which there are none, but a new page added by hand should
          // not silently lose the link.
          editUrl: `${repository}/edit/main/website/content/`,
          showLastUpdateTime: true,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
        sitemap: {
          lastmod: 'date',
          changefreq: null,
          priority: null,
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    [
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: '/docs',
        highlightSearchTermsOnTargetPage: true,
        explicitSearchResultPath: true,
      },
    ],
  ],

  themeConfig: {
    image: 'img/mire-mark.svg',
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'mire',
      logo: {
        alt: 'mire',
        src: 'img/mire-mark.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'documentation',
          position: 'left',
          label: 'Documentation',
        },
        {
          to: '/docs/reference/api',
          position: 'left',
          label: 'API',
        },
        {
          to: '/docs/internals/architecture',
          position: 'left',
          label: 'Architecture',
        },
        {
          href: repository,
          position: 'right',
          className: 'navbar-github',
          'aria-label': 'GitHub repository',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Documentation',
          items: [
            { label: 'Introduction', to: '/docs/intro' },
            { label: 'Installation', to: '/docs/getting-started/installation' },
            { label: 'Your first call', to: '/docs/getting-started/first-call' },
            { label: 'Command line and options', to: '/docs/reference/cli' },
          ],
        },
        {
          title: 'Internals',
          items: [
            { label: 'Architecture', to: '/docs/internals/architecture' },
            {
              label: 'Decisions',
              to: '/docs/internals/decisions/0001-push-configuration-reloads-to-the-browser',
            },
            { label: 'Contributing', to: '/docs/project/contributing' },
          ],
        },
        {
          title: 'Project',
          items: [
            { label: 'GitHub', href: repository },
            { label: 'Releases', href: `${repository}/releases` },
            { label: 'Issues', href: `${repository}/issues` },
            {
              label: 'Container image',
              href: `https://github.com/${organization}/${project}/pkgs/container/${project}`,
            },
          ],
        },
      ],
      copyright: `Apache-2.0. Documentation built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'json', 'yaml', 'rust', 'toml', 'docker'],
    },
  } satisfies Preset.ThemeConfig,
}

export default config
