import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Explicit rather than autogenerated: the order these are read in is a
// decision, and most of the pages are synced from files that know nothing about
// the site. The one exception is the decision records, which are numbered and
// arrive by the file — a new ADR should not need an edit here.
const sidebars: SidebarsConfig = {
  documentation: [
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      link: { type: 'doc', id: 'intro' },
      items: ['getting-started/installation', 'getting-started/first-call'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        { type: 'doc', id: 'guides/configuration', label: 'Configuration' },
        { type: 'doc', id: 'guides/models', label: 'Models' },
        { type: 'doc', id: 'guides/auth', label: 'Credentials' },
        { type: 'doc', id: 'guides/mcp', label: 'MCP servers' },
        { type: 'doc', id: 'guides/agent-loop', label: 'The agent loop' },
        { type: 'doc', id: 'guides/streaming', label: 'Streaming' },
        { type: 'doc', id: 'guides/embeddings', label: 'Embeddings' },
        { type: 'doc', id: 'guides/ui', label: 'The web UI' },
        { type: 'doc', id: 'guides/dev-stack', label: 'A stack to test against' },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        { type: 'doc', id: 'reference/cli', label: 'Command line and options' },
        { type: 'doc', id: 'reference/configuration-keys', label: 'Configuration keys' },
        { type: 'doc', id: 'reference/api', label: 'HTTP API' },
      ],
    },
    {
      type: 'category',
      label: 'Internals',
      collapsed: false,
      items: [
        { type: 'doc', id: 'internals/architecture', label: 'Architecture' },
        {
          type: 'category',
          label: 'Decisions',
          link: { type: 'doc', id: 'internals/decisions/index' },
          items: [{ type: 'autogenerated', dirName: 'internals/decisions' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Project',
      collapsed: false,
      items: [{ type: 'doc', id: 'project/contributing', label: 'Contributing' }],
    },
  ],
}

export default sidebars
